name: zero_waste_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
organization: com.aa

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.17
  collection: ^1.16.0
  uuid: ^3.0.4
  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0
  shared_preferences: ^2.0.13
  sqflite: ^2.0.2+1
  path: ^1.8.0
  path_provider: ^2.0.11
  intl: ^0.19.0
  http: ^1.2.1
  csv: ^6.0.0
  googleapis: ^13.1.0
  googleapis_auth: ^1.3.0
  camera: ^0.11.0+1
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/credentials/vision_api_key.json
    - assets/images/learn_title.png
    - assets/images/learn1.png
    - assets/images/learn2.png
    - assets/images/learn3.png
    - assets/images/learn4.png
    - assets/images/learn5.png
    - assets/images/learn6.png
    - assets/images/learn7.png
    - assets/images/learn8.png
    - assets/images/learn9.png
    - assets/images/learn10.png
    - assets/images/learn11.png
    - assets/images/learn12.png
    - assets/images/map.png
    - assets/images/search_title.png
    - assets/images/search_result_title.png
    - assets/images/profile_title.png
    - assets/images/result_title.png
    - assets/images/camera_title.png
    - assets/images/camera_result_title.png
    - assets/images/logo.png
    - assets/images/action_title.png
    - assets/images/login.png
    - assets/images/signup.png
    - assets/images/home_image.png
    - assets/images/background.png
    - assets/images/categories/plastic.png
    - assets/images/categories/glass.png
    - assets/images/categories/paper.png
    - assets/images/categories/metal.png
    - assets/images/categories/electronics.png
    - assets/images/categories/light_bulbs.png
    - assets/images/categories/styrofoam.png
    - assets/images/categories/food_scraps.png
    - assets/images/categories/clothing.png
    - assets/images/categories/medication.png
    - assets/images/sustainable_alternatives/reusable_bottle.png
    - assets/images/sustainable_alternatives/recycle_paper.png
    - assets/images/sustainable_alternatives/compost_vegetable_peels.png
    - assets/images/sustainable_alternatives/donate_old_clothing.png
    - assets/images/sustainable_alternatives/e_waste.png
    - assets/images/sustainable_alternatives/use_led_bulbs.png
    - assets/images/sustainable_alternatives/recycle_glass_bottles.png
    - assets/data/sites.csv
    - assets/data/Zero_Waste.csv
    - assets/data/badges.csv
    - assets/data/xp.csv
    - assets/images/badges/badge_bronze.png
    - assets/images/badges/badge_silver.png
    - assets/images/badges/badge_gold.png
    - assets/images/badges/badge_platinum.png
    - assets/images/badges/badge_diamond.png
    - assets/images/badges/badge_coming.png
    - assets/images/items/3MStickyNotes.png
    - assets/images/items/AirConditioner.png
    - assets/images/items/Alkaline_SingleUse_Batteries.png
    - assets/images/items/AluminumCan.png
    - assets/images/items/AluminumFoil.png
    - assets/images/items/AluminumSiding.png
    - assets/images/items/Automotive_LeadAcid_Batteries.png
    - assets/images/items/Bedding.png
    - assets/images/items/Belts.png
    - assets/images/items/Books.png
    - assets/images/items/Bread.png
    - assets/images/items/Brochures.png
    - assets/images/items/BusinessCards.png
    - assets/images/items/Calendars.png
    - assets/images/items/CarbonZinc_SingleUse_Batteries.png
    - assets/images/items/CardboardBoxesEtc.png
    - assets/images/items/CardboardFoodDeliveryBoxes.png
    - assets/images/items/CardboardMovingBoxes.png
    - assets/images/items/CardboardPackaging.png
    - assets/images/items/CardboardProductPackagingBoxes.png
    - assets/images/items/CardboardRetailBoxes.png
    - assets/images/items/CardboardShippingBoxes.png
    - assets/images/items/CardboardStorageBoxes.png
    - assets/images/items/CardboardTubes.png
    - assets/images/items/CarParts.png
    - assets/images/items/CeramicArtPieces.png
    - assets/images/items/CeramicBowls.png
    - assets/images/items/CeramicCookware.png
    - assets/images/items/CeramicEtc.png
    - assets/images/items/CeramicFigurines.png
    - assets/images/items/CeramicMugs.png
    - assets/images/items/CeramicPenHolders.png
    - assets/images/items/CeramicPlanters.png
    - assets/images/items/CeramicPlates.png
    - assets/images/items/CeramicTiles.png
    - assets/images/items/CeramicVases.png
    - assets/images/items/ClothingEtc.png
    - assets/images/items/CoffeeGrounds.png
    - assets/images/items/CompactFluorescentLamps_CFLs_.png
    - assets/images/items/CookingOil.png
    - assets/images/items/Copier.png
    - assets/images/items/CorrugatedCardboard.png
    - assets/images/items/DairyProducts.png
    - assets/images/items/DeadFlowers.png
    - assets/images/items/DesktopPC.png
    - assets/images/items/DVDPlayer.png
    - assets/images/items/Eggshells.png
    - assets/images/items/ElectricShaver.png
    - assets/images/items/ElectricToothbrush.png
    - assets/images/items/ElectronicsEtc.png
    - assets/images/items/Envelopes.png
    - assets/images/items/ExcessSoil.png
    - assets/images/items/FacialTissues.png
    - assets/images/items/FallenFruit.png
    - assets/images/items/FallenLeaves.png
    - assets/images/items/FaxMachine.png
    - assets/images/items/FileFolders.png
    - assets/images/items/FluorescentTubes.png
    - assets/images/items/Flyers.png
    - assets/images/items/FoodScrapsEtc.png
    - assets/images/items/FruitPeels.png
    - assets/images/items/GameConsole.png
    - assets/images/items/GardenWeeds.png
    - assets/images/items/GlassBeerBottle.png
    - assets/images/items/GlassBowl.png
    - assets/images/items/GlassBrick.png
    - assets/images/items/GlassCandleHolder.png
    - assets/images/items/GlassCosmeticJar.png
    - assets/images/items/GlassDoor.png
    - assets/images/items/GlassDrinkingGlass.png
    - assets/images/items/GlassEtc.png
    - assets/images/items/GlassJamJar.png
    - assets/images/items/GlassJuiceBottle.png
    - assets/images/items/GlassLampShade.png
    - assets/images/items/GlassMedicineBottle.png
    - assets/images/items/GlassOliveOilBottle.png
    - assets/images/items/GlassPerfumeBottle.png
    - assets/images/items/GlassPickleJar.png
    - assets/images/items/GlassPictureFrame.png
    - assets/images/items/GlassPitcher.png
    - assets/images/items/GlassPlate.png
    - assets/images/items/GlassSauceBottle.png
    - assets/images/items/GlassSodaBottle.png
    - assets/images/items/GlassTile.png
    - assets/images/items/GlassVase.png
    - assets/images/items/GlassWaterBottle.png
    - assets/images/items/Gloves.png
    - assets/images/items/GrassClippings.png
    - assets/images/items/HairDryer.png
    - assets/images/items/HalogenBulbs.png
    - assets/images/items/Hats.png
    - assets/images/items/Headphones.png
    - assets/images/items/IncandescentBulbs.png
    - assets/images/items/Inhalers.png
    - assets/images/items/Insulation.png
    - assets/images/items/IrrigationTubing.png
    - assets/images/items/Keyboard.png
    - assets/images/items/Laptop.png
    - assets/images/items/LargeBranches.png
    - assets/images/items/LEDBulbs.png
    - assets/images/items/LeftoverFood.png
    - assets/images/items/LetterheadPaper.png
    - assets/images/items/LightBulbsEtc.png
    - assets/images/items/LiquidMedications.png
    - assets/images/items/Magazines.png
    - assets/images/items/MeatScraps.png
    - assets/images/items/MedicationEtc.png
    - assets/images/items/MetalBakingSheets.png
    - assets/images/items/MetalCutlery.png
    - assets/images/items/MetalDrillBits.png
    - assets/images/items/MetalEngineParts.png
    - assets/images/items/MetalEtc.png
    - assets/images/items/MetalFurniture.png
    - assets/images/items/MetalHammer.png
    - assets/images/items/MetalHangers.png
    - assets/images/items/MetalPen.png
    - assets/images/items/MetalPipes.png
    - assets/images/items/MetalPotsandPans.png
    - assets/images/items/MetalRoofing.png
    - assets/images/items/MetalScissors.png
    - assets/images/items/MetalScrewdriver.png
    - assets/images/items/MetalStapler.png
    - assets/images/items/MetalWaterBottle_Aluminum_.png
    - assets/images/items/MetalWaterBottle_Copper_.png
    - assets/images/items/MetalWaterBottle_StainlessSteel_.png
    - assets/images/items/MetalWheels.png
    - assets/images/items/MetalWrench.png
    - assets/images/items/Microphone.png
    - assets/images/items/Microwave.png
    - assets/images/items/Monitor.png
    - assets/images/items/Mouse.png
    - assets/images/items/Newspaper.png
    - assets/images/items/NickelCadmiumBatteries.png
    - assets/images/items/NickelMetalHydrideBatteries.png
    - assets/images/items/NotebookPaper.png
    - assets/images/items/Notepads.png
    - assets/images/items/NutShells.png
    - assets/images/items/OldClothes.png
    - assets/images/items/OldMulch.png
    - assets/images/items/Over-the-CounterMedications.png
    - assets/images/items/PaperArtSupplies.png
    - assets/images/items/PaperBags.png
    - assets/images/items/PaperCups.png
    - assets/images/items/PaperDecorations.png
    - assets/images/items/PaperDrinkSleeves.png
    - assets/images/items/PaperEggCartons.png
    - assets/images/items/PaperEtc.png
    - assets/images/items/PaperFans.png
    - assets/images/items/PaperGiftBoxes.png
    - assets/images/items/PaperLanterns.png
    - assets/images/items/PaperMailingTubes.png
    - assets/images/items/PaperNapkins.png
    - assets/images/items/PaperPlates.png
    - assets/images/items/PaperTablecloth.png
    - assets/images/items/PaperTowels.png
    - assets/images/items/PaperWrapping.png
    - assets/images/items/Patches_nicotine_hormone_.png
    - assets/images/items/PetMedications.png
    - assets/images/items/PizzaBoxes.png
    - assets/images/items/PlasticBags.png
    - assets/images/items/PlasticBaskets.png
    - assets/images/items/PlasticBinder.png
    - assets/images/items/PlasticBottlesEtc.png
    - assets/images/items/PlasticBreadBag.png
    - assets/images/items/PlasticBubbleWrap.png
    - assets/images/items/PlasticButtons.png
    - assets/images/items/PlasticClearCups.png
    - assets/images/items/PlasticColoredCups.png
    - assets/images/items/Plasticcup.png
    - assets/images/items/PlasticCuttingBoard.png
    - assets/images/items/PlasticDetergentBottles.png
    - assets/images/items/PlasticDryCleanerBags.png
    - assets/images/items/PlasticEtc.png
    - assets/images/items/PlasticFolder.png
    - assets/images/items/PlasticFoodContainers_PEP_HDPE_.png
    - assets/images/items/PlasticFoodPackagingEtc.png
    - assets/images/items/PlasticForks.png
    - assets/images/items/PlasticFurniture.png
    - assets/images/items/PlasticGardenPots.png
    - assets/images/items/PlasticGroceryBags.png
    - assets/images/items/PlasticHairBrush.png
    - assets/images/items/PlasticHangers.png
    - assets/images/items/PlasticIceCreamTub.png
    - assets/images/items/PlasticJuiceBottle.png
    - assets/images/items/PlasticKnives.png
    - assets/images/items/PlasticLotionBottle.png
    - assets/images/items/PlasticMilkJugs.png
    - assets/images/items/PlasticMulchFilm.png
    - assets/images/items/PlasticNewspaperBag.png
    - assets/images/items/PlasticPen.png
    - assets/images/items/PlasticPipes.png
    - assets/images/items/PlasticPlates.png
    - assets/images/items/PlasticSaladContainer.png
    - assets/images/items/PlasticSeedTrays.png
    - assets/images/items/PlasticShampooBottles.png
    - assets/images/items/PlasticShippingEnvelopes.png
    - assets/images/items/PlasticShippingPillows.png
    - assets/images/items/PlasticShoeSoles_PET_.png
    - assets/images/items/PlasticShoeSoles_PVC_.png
    - assets/images/items/PlasticSiding.png
    - assets/images/items/PlasticSnackWrapper.png
    - assets/images/items/PlasticSodaBottles.png
    - assets/images/items/PlasticSoloCups.png
    - assets/images/items/PlasticSpoons.png
    - assets/images/items/PlasticStirSticks.png
    - assets/images/items/PlasticStorageContainers.png
    - assets/images/items/PlasticStraws.png
    - assets/images/items/PlasticTakeoutContainer_Clamshell_.png
    - assets/images/items/PlasticToothbrush.png
    - assets/images/items/PlasticToys.png
    - assets/images/items/PlasticUtensilsEtc.png
    - assets/images/items/PlasticWaterBottles.png
    - assets/images/items/PlasticWrap.png
    - assets/images/items/PlasticYogurtCup.png
    - assets/images/items/PlasticZiplocBags.png
    - assets/images/items/PlasticZippers.png
    - assets/images/items/PlywoodSheets.png
    - assets/images/items/PrescriptionMedications.png
    - assets/images/items/PrintedPaper.png
    - assets/images/items/Printer.png
    - assets/images/items/Projector.png
    - assets/images/items/PrunedPlantMaterial.png
    - assets/images/items/RechargeableBatteries.png
    - assets/images/items/Refrigerator.png
    - assets/images/items/Scanner.png
    - assets/images/items/Scarves.png
    - assets/images/items/Shoes.png
    - assets/images/items/ShreddedPaper.png
    - assets/images/items/SmallBranches.png
    - assets/images/items/Smartphone.png
    - assets/images/items/Smartwatch.png
    - assets/images/items/Speakers.png
    - assets/images/items/SteelBeams.png
    - assets/images/items/SteelCan.png
    - assets/images/items/SteelFoodContainer.png
    - assets/images/items/StickyPaperLabels_AddressLabels_.png
    - assets/images/items/StyrofoamBlocks.png
    - assets/images/items/StyrofoamConcreteForms.png
    - assets/images/items/StyrofoamContainer.png
    - assets/images/items/StyrofoamCraftMaterials.png
    - assets/images/items/StyrofoamCups.png
    - assets/images/items/StyrofoamEtc.png
    - assets/images/items/StyrofoamInsulationPanels.png
    - assets/images/items/StyrofoamMedicalCoolers.png
    - assets/images/items/StyrofoamPackingPeanuts.png
    - assets/images/items/StyrofoamPlates.png
    - assets/images/items/StyrofoamTrays.png
    - assets/images/items/SupplementsandVitamins.png
    - assets/images/items/Tablet.png
    - assets/images/items/TeaBags.png
    - assets/images/items/Television.png
    - assets/images/items/TinCan.png
    - assets/images/items/ToiletPaper.png
    - assets/images/items/TornClothes.png
    - assets/images/items/Towels.png
    - assets/images/items/UsedSyringes.png
    - assets/images/items/VacuumCleaner.png
    - assets/images/items/VegetablePeels.png
    - assets/images/items/WashingMachine.png
    - assets/images/items/WindowGlass.png
    - assets/images/items/WineBottle.png
    - assets/images/items/WoodenBeams.png
    - assets/images/items/WoodenCraftMaterials.png
    - assets/images/items/WoodenCrates.png
    - assets/images/items/WoodenDecorations.png
    - assets/images/items/WoodenEtc.png
    - assets/images/items/WoodenFlooring.png
    - assets/images/items/WoodenFurniture.png
    - assets/images/items/WoodenHandTools.png
    - assets/images/items/WoodenPallets.png
    - assets/images/items/WoodenUtensils.png
    - assets/images/items/YardWasteEtc.png